CLaundarete/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('', include('backend.urls')),
    path('api/', include('api.urls')),
]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from django.urls.conf import include
from . import views
from rest_framework_nested import routers

router = routers.DefaultRouter()
router.register('complaints', views.ComplaintViewSet)
router.register('launderers', views.LaundererViewSet)
router.register('clients', views.ClientViewSet)
router.register('users', views.CLUserViewSet)
router.register('launderettes', views.LaunderetteViewSet)
router.register('services', views.ServicesViewSet)
router.register('reviews', views.ReviewViewSet)
router.register('review-comments', views.ReviewCommentViewSet)
router.register('orders', views.OrderViewSet)

launderette_router = routers.NestedDefaultRouter(router, 'launderettes', lookup='launderette')
launderette_router.register('reviews', views.ReviewViewSet, basename="launderette-reviews")
launderette_router.register('services', views.ServicesViewSet, basename="launderette-services")
launderette_router.register('orders', views.OrderViewSet, basename="launderette-orders")

client_router = routers.NestedDefaultRouter(router, 'clients', lookup='client')
client_router.register('reviews', views.ReviewViewSet, basename="client-reviews")
client_router.register('orders', views.OrderViewSet, basename="client-orders")
client_router.register('complaints', views.ComplaintViewSet, basename="client-complaints")

launderer_router = routers.NestedDefaultRouter(router, 'launderers', lookup='launderer')
launderer_router.register('launderettes', views.LaundererLaunderetteViewSet, basename="launderer-launderettes")
launderer_router.register('complaints', views.ComplaintViewSet, basename="launderer-complaints")

review_router = routers.NestedDefaultRouter(router, 'reviews', lookup='review')
review_router.register('review-comments', views.ReviewCommentViewSet, basename="review-reviewcomments")

urlpatterns = [
    path('', include(router.urls)),
    path('', include(launderette_router.urls)),
    path('', include(client_router.urls)),
    path('', include(launderer_router.urls)),
    path('', include(review_router.urls)),
]

backend/forms.py
from django.forms import ModelForm
from .models import *
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class DateInput(forms.DateInput):
    input_type = 'date'

class CreatUserForm(UserCreationForm):
    name = forms.CharField(max_length=30, required=True, help_text='Full Name.', label='Full Name')
    address = forms.CharField(max_length=30, required=False, help_text='Your address.', label='Address')
    city = forms.CharField(max_length=30, required=True, help_text='Your city name.', label='City')
    easypaisa_account = forms.CharField(max_length=30,  help_text='Your easypaisa account', label='City')
    class Meta:
        model =  User
        fields =  ['username', 'name', 'city', 'easypaisa_account', 'address', 'email', 'password1', 'password2']
        
    def clean(self):
 
        super(CreatUserForm, self).clean()
         
        name = self.cleaned_data.get('name')
        address = self.cleaned_data.get('address')
        city = self.cleaned_data.get('city')
        username = self.cleaned_data.get('username')
        easypaisa_account = self.cleaned_data.get('easypaisa_account')
 
        if len(city) < 5:
            self._errors['city'] = self.error_class([
                'City minimum character should be 5.'])
        if len(name) < 4:
            self._errors['name'] = self.error_class([
                'Name should contain a minimum of 4 characters'])
        if len(username) < 4:
            self._errors['username'] = self.error_class([
                'Username should contain a minimum of 4 characters'])
        if len(address) < 5:
            self._errors['address'] = self.error_class([
                'Address can not be less 5 characters'])
        if len(easypaisa_account) != 11:
            self._errors['easypaisa_account'] = self.error_class([
                'Easypaisa account number should be 11'])
 
        return self.cleaned_data

class ServicesForm(ModelForm):
    
    class Meta:
        model = Services
        fields = '__all__'
        exclude = ['launderette']
    
    def clean(self):
 
        super(ServicesForm, self).clean()
         
        title = self.cleaned_data.get('title')
        price = self.cleaned_data.get('price')
 
        if price < 5:
            self._errors['price'] = self.error_class([
                'Minimum price can be 5.'])
        if len(title) < 5:
            self._errors['title'] = self.error_class([
                'Service Title Should Contain a minimum of 5 characters'])
 
        return self.cleaned_data


class LaundererForm(ModelForm):
    
    class Meta:
        model = Launderer
        fields = '__all__'
        exclude = ['user']       
    
    def clean(self):
 
        super(LaundererForm, self).clean()
         
        name = self.cleaned_data.get('name')
        address = self.cleaned_data.get('address')
        city = self.cleaned_data.get('city')
        easypaisa_account = self.cleaned_data.get('easypaisa_account')
        latitude = self.cleaned_data.get('lat')
        longitude = self.cleaned_data.get('lon')
 
        if len(city) < 5:
            self._errors['city'] = self.error_class([
                'City minimum character should be 5.'])
        if len(name) < 4:
            self._errors['name'] = self.error_class([
                'Name should contain a minimum of 4 characters'])
        if len(address) < 5:
            self._errors['address'] = self.error_class([
                'Address can not be less 5 characters'])
        if len(easypaisa_account) != 11:
            self._errors['easypaisa_account'] = self.error_class([
                'Easypaisa account number should be 11'])
        if latitude > -90 and latitude < 90:
            pass
        else:
            self._errors['lat'] = self.error_class([
                'Latitude must be greater than -90 and less than  90'])
        
        if longitude > -180 and longitude < 180:
            pass
        else:
            self._errors['lon'] = self.error_class([
                'Longitude must be greater than -180 and less than 180'])
 

        return self.cleaned_data


class LaunderetteForm(ModelForm):
    
    class Meta:
        model = Launderette
        fields = '__all__'
        exclude = ['launderer']
        
    def clean(self):
 
        super(LaunderetteForm, self).clean()
         
        name = self.cleaned_data.get('name')
        location = self.cleaned_data.get('location')
        available_time = self.cleaned_data.get('available_time')
 
        if len(available_time) < 5:
            self._errors['available_time'] = self.error_class([
                'Available time minimum character should be 5.'])
        if len(name) < 4:
            self._errors['name'] = self.error_class([
                'Name should contain a minimum of 4 characters'])
        if len(location) < 5:
            self._errors['location'] = self.error_class([
                'Location can not be less 5 characters'])
 
        return self.cleaned_data

class ReviewCommentForm(ModelForm):
    comment=forms.CharField(widget=forms.Textarea(attrs={"rows":5,  }))
    
    class Meta:
        model = ReviewComment
        exclude = '__all__'
        fields = ['comment']
    
    def clean(self):
 
        super(ReviewCommentForm, self).clean()
         
        comment = self.cleaned_data.get('comment')
 
        if len(comment) < 4:
            self._errors['comment'] = self.error_class([
                'Comment minimum character should be 4.'])


class LaundererProfilePicForm(ModelForm):
    
    class Meta:
        model = Launderer
        fields = ['profile_pic']


class LaundererEmailForm(ModelForm):
    
    class Meta:
        model = User
        fields = ['email']

class ComplaintForm(ModelForm):
    complain=forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":50}))
    response=forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":50}), required=False)

    class Meta:
        model = Complaint
        fields = ["complain", "response", 'subject']
    
    def clean(self):
 
        super(ComplaintForm, self).clean()
         
        complain = self.cleaned_data.get('complain')
 
        if len(complain) < 4:
            self._errors['complain'] = self.error_class([
                'Complain minimum character should be 4.'])

frontend/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/frontend/admin/clientDetail.html
{%  extends 'frontend/admin/partialview/base_template.html' %}
{% load static %}

{% block content %}


<div class="page">

  {% include 'frontend/admin/partialview/top_navbar.html' %}

  <!-- Breadcrumb-->
  <div class="breadcrumb-holder">
    <div class="container-fluid">
      <ul class="breadcrumb">
        <li class="breadcrumb-item "><a href="{% url 'adminDashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item "><a href="{% url 'adminClients' %}">Clients</a></li>
        <li class="breadcrumb-item active"><a>Clients</a></li>
      </ul>
    </div>
  </div>

  <h1 class="display-3 text-center m-4">Clients</h1>
  <hr>
  <section class="charts">
    <div class="container-fluid">
      <!-- Page Header-->
      <div class="card line-chart-example">
        <div class="card-header d-flex align-items-center">

          <img src="{{client.profile_pic.url}}" alt="person" class="img-fluid rounded-circle" width="300">
        </div>
        <div class="card-body">

          <div class="row">
            <div class="col">
              <p class="lead text-primary">Name:</p>
              <p class="lead ">{{client.name}}</p>
            </div>

            <div class="col">
              <p class="lead text-primary">Username:</p>
              <p class="lead ">{{client.user.username}}</p>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <p class="lead text-primary">Email:</p>
              <p class="lead ">{{client.user.email}}</p>
            </div>

            <div class="col">
              <p class="lead text-primary">Address:</p>
              <p class="lead ">{{client.address}}</p>
            </div>
          </div>

        </div>
        <div class="card-footer">
          <p class="lead text-primary">Date Joined:</p>
          <p class="lead ">{{client.date_joined}}</p>

          {% if client.isBlocked == False %}
          <form enctype="multipart/form-data" method="POST" action="{% url 'clientRequestProcess' client.id %}">
            {% csrf_token %}
            <div class="form-group">
              <input type="hidden" id="statusField1" name="statusField" value="block">
            </div>
            <div class="form-group mt-4">
              <input type="submit" onclick="return confirm('Are you sure you want to block this user?')" value="Block Client" class="btn btn-md btn-outline-danger px-4">
            </div>
          </form>
          {% endif %}
          {% if client.isBlocked == True %}
          <form enctype="multipart/form-data" method="POST" action="{% url 'clientRequestProcess' client.id %}">
            {% csrf_token %}
            <div class="form-group">
              <input type="hidden" id="statusField1" name="statusField" value="unblock">
            </div>
            <div class="form-group mt-4">
              <input type="submit" value="Unblock Client" onclick="return confirm('Are you sure you want to unblock this user?')" class="btn btn-md btn-outline-success px-4">
            </div>
          </form>
          {% endif %}
        </div>
      </div>

    </div>
  </section>

  <section class="charts">
    <div class="container-fluid">
      <!-- Page Header-->
      <header>
        <h1 class="h3 display">Orders </h1>
      </header>

      <div class="card">

        <div class="card-header">

          Ongoing Orders

        </div>


        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Date & Time Started</th>
                  <th>Launderette</th>
                  <th>Status</th>
                  <th>Price</th>
                  <th>Amount</th>
                  <th>Delivery Time</th>
                  <th>Change status</th>
                </tr>
              </thead>
              <tbody>
                {% for orders in orders %}
                <tr>
                  <td>{{orders.date_started}}</td>
                  <td>{{orders.launderette}}</td>
                  <td>{{orders.status}}</td>
                  <td>{{orders.price}}</td>
                  <td>{{orders.amount}}</td>
                  <td>{{orders.date_end}}</td>
                  <td><a class="btn btn-md btn-outline-primary"
                      href="{% url 'adminOrderDetails' orders.id %}">Details</a></td>
                </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>



    </div>
  </section>

  <footer class="main-footer">

    {% include 'frontend/admin/partialview/footer_navbar.html' %}
  </footer>
</div>


{% endblock content %}

frontend/templates/frontend/admin/complaintDetail.html
{%  extends 'frontend/admin/partialview/base_template.html' %}
{% load static %}

{% block content %}


<div class="page">

  {% include 'frontend/admin/partialview/top_navbar.html' %}


  <!-- Breadcrumb-->
  <div class="breadcrumb-holder">
    <div class="container-fluid">
      <ul class="breadcrumb">
        <li class="breadcrumb-item "><a href="{% url 'adminDashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'adminComplaints' %}">Complaint</a></li>
        <li class="breadcrumb-item active"><a>Details</a></li>
      </ul>
    </div>
  </div>

  <div class="container mx-4 px-4">
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
  </div>

  <h1 class="h3 display-3 text-primary m-4 text-center"> Complaint Details </h1>


  <section class="charts">
    <div class="container-fluid">
      <!-- Page Header-->
      <div class="card line-chart-example">
        <div class="card-header d-flex align-items-center">
          <h4>Complaint</h4>
        </div>
        <div class="card-body">

          <div class="row">
            <div class="col-6">
              <p class="lead text-primary">By:</p>
              {% if complaint.client == None %}
              <p class="lead "><a href="{% url 'adminLaundererDetail' complaint.launderer.id %}">{{complaint.launderer}}</a></p>
              {% else %}
              <p class="lead "><a href="{% url 'adminClientDetail' complaint.client.id %}">{{complaint.client}}</a></p>
              {% endif %}
            </div>
            <div class="col-6">
              <p class="lead text-primary">Subject:</p>
              <p class="lead ">{{complaint.subject}}</p>
            </div>
          </div>

          <p class="lead text-primary">Complain:</p>
          <p class="lead">{{complaint.complain}}</p>

          {% if complaint.response != None %}
          <p class="lead text-primary">Response:</p>
          <p class="lead">{{complaint.response}}</p>
          {% endif %}


          <div class="row">
            <div class="col-6">
              <p class="lead text-primary">Status:</p>
              <p class="lead ">{{complaint.status}}</p>
            </div>

            <div class="col-6">
              <p class="lead text-primary">Sent Time:</p>
              <p class="lead ">{{complaint.date}}</p>
            </div>
          </div>
        </div>
      </div>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_response">Response:</label>
          <br>
          {{form.response}}
          {{form.response.errors}}
        </div>
        <div class="form-group">
          <input type="submit" value="Post" class="btn btn-primary">
        </div>
      </form>
    </div>

  </section>






  <footer class="main-footer">
    {% include 'frontend/admin/partialview/footer_navbar.html' %}
  </footer>
</div>


{% endblock content %}

frontend/templates/frontend/admin/complaints.html
{%  extends 'frontend/admin/partialview/base_template.html' %}
{% load static %}

{% block content %}


<div class="page">

  {% include 'frontend/admin/partialview/top_navbar.html' %}

  <!-- Breadcrumb-->
  <div class="breadcrumb-holder">
    <div class="container-fluid">
      <ul class="breadcrumb">
        <li class="breadcrumb-item "><a href="{% url 'adminDashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item active">Complaints </li>
      </ul>
    </div>
  </div>

  <div class="container mx-4 px-4">
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
  </div>
  <section class="charts my-4">
    <div class="container-fluid">


      <div class="card">
        <div class="container mt-4">

          <form method="get" class="text-left">
            <div class="filters">
              <div class="form-group-material">
                <label>Subject & Status</label>
                {{complaintsFilter.form.subject}}
                {{complaintsFilter.form.subject.errors}}
                <br>
                {{complaintsFilter.form.status}}
              </div>

              <a href="#date_filter" data-toggle="collapse">Date Filters</a>
              <div id="date_filter" class="collapse">
                <div class="form-group-material ">
                  <label>Date Range</label>
                  {{complaintsFilter.form.start_date}}
                  {{complaintsFilter.form.start_date.errors}}
                  {{complaintsFilter.form.end_date}}
                  {{complaintsFilter.form.end_date.errors}}
                </div>
              </div>
            </div>
            <div class="form-group">
              <button class="my-btn btn btn-primary" type="submit">Search</button>
            </div>
          </form>
        </div>

        <div class="card-header">

          User Complaints List

        </div>


        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>User</th>
                  <th>Subject</th>
                  <th>Status</th>
                  <th>Details</th>
                </tr>
              </thead>
              <tbody>
                {% for complaint in complaints %}
                <tr>
                  <td>{{complaint.date}}</td>
                  {% if complaint.client == None %}
                  <td>{{complaint.launderer}}</td>
                  {% else %}
                  <td>{{complaint.client}}</td>
                  {% endif %}
                  <td>{{complaint.subject}}</td>
                  <td>{{complaint.status}}</td>
                  <td><a class="btn btn-md btn-outline-primary"
                      href="{% url 'adminComplaintsDetail' complaint.id %}">Check</a></td>
                </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>

      {% if complaints.has_previous %}
      <a href="{% url 'adminComplaints' %}?page={{complaints.previous_page_number}}">Previous Page</a>
      {% endif %}
      {% if complaints.has_next %}
      <a href="{% url 'adminComplaints' %}?page={{complaints.next_page_number}}">Next Page</a>
      {% endif %}
    </div>
  </section>

  <footer class="main-footer">
    {% include 'frontend/admin/partialview/footer_navbar.html' %}
  </footer>
</div>

<script>
  toastr.options = {
    "closeButton": true,
    "debug": false,
    "newestOnTop": true,
    "progressBar": true,
    "positionClass": "toast-top-center",
    "preventDuplicates": true,
    "onclick": null,
    "showDuration": "300",
    "hideDuration": "1000",
    "timeOut": "5000",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
  }

  //Query All input fields
  var form_fields = document.getElementsByTagName('input')
  var i = 0
  for (var field in form_fields) {
    console.log(form_fields[field].name)
    form_fields[field].className += ' form-control'
  }
  form_fields[0].placeholder = "Enter subject"
  form_fields[1].placeholder = "Date started (eg: 11-09-2021)"
  form_fields[2].placeholder = "Date Ended (eg: 05-12-2021)"

  $(document).ready(function () {
    if ($(".errorlist").length) {
      $(".errorlist").parent().parent().prev("a").css({
        "color": "#dd0303"
      });
    }
  });
  var formErrors = document.getElementsByClassName("errorlist");
  if (formErrors.length) {
    for (var field in formErrors) {
      console.log(formErrors[field]);
      myUl = formErrors[field];
      items = myUl.getElementsByTagName("li");
      for (var item in items) {
        if (items[item].textContent !== undefined) {
          toastr.error(items[item].textContent)
        }
      }
    }
  }
</script>

{% endblock content %}

frontend/templates/frontend/admin/laundererDetail.html
{%  extends 'frontend/admin/partialview/base_template.html' %}
{% load static %}

{% block content %}


<div class="page">

  {% include 'frontend/admin/partialview/top_navbar.html' %}

  <!-- Breadcrumb-->
  <div class="breadcrumb-holder">
    <div class="container-fluid">
      <ul class="breadcrumb">
        <li class="breadcrumb-item "><a href="{% url 'adminDashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item "><a href="{% url 'adminLaunderers' %}">Launderers</a></li>
        <li class="breadcrumb-item active"><a>Details</a></li>
      </ul>
    </div>
  </div>

  <h1 class="display-3 text-center m-4">Launderer</h1>
  <hr>
  <section class="charts">
    <div class="container-fluid">
      <!-- Page Header-->
      <div class="card line-chart-example">
        <div class="card-header d-flex align-items-center">

          <img src="{{launderer.profile_pic.url}}" alt="person" class="img-fluid rounded-circle" width="300">
        </div>
        <div class="card-body">

          <div class="row">
            <div class="col">
              <p class="lead text-primary">Name:</p>
              <p class="lead ">{{launderer.name}}</p>
            </div>

            <div class="col">
              <p class="lead text-primary">Username:</p>
              <p class="lead ">{{launderer.user.username}}</p>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <p class="lead text-primary">Email:</p>
              <p class="lead ">{{launderer.user.email}}</p>
            </div>

            <div class="col">
              <p class="lead text-primary">City:</p>
              <p class="lead ">{{launderer.city}}</p>
            </div>

            <div class="col">
              <p class="lead text-primary">Address:</p>
              <p class="lead ">{{launderer.address}}</p>
            </div>
            
            <div class="col">
              <p class="lead text-primary">Latitude:</p>
              <p class="lead ">{{launderer.lat}}</p>
            </div>
            <div class="col">
              <p class="lead text-primary">Longitude:</p>
              <p class="lead ">{{launderer.lon}}</p>
            </div>
          </div>

        </div>
        <div class="card-footer">
          <p class="lead text-primary">Date Joined:</p>
          <p class="lead ">{{launderer.date_joined}}</p>

          {% if launderer.isBlocked == False %}
          <form enctype="multipart/form-data" method="POST" action="{% url 'laundererRequestProcess' launderer.id %}">
            {% csrf_token %}
            <div class="form-group">
              <input type="hidden" id="statusField1" name="statusField" value="block">
            </div>
            <div class="form-group mt-4">
              <input type="submit" value="Block Launderer" onclick="return confirm('Are you sure you want to block this user?')" class="btn btn-md btn-outline-danger px-4">
            </div>
          </form>
          {% endif %}
          {% if launderer.isBlocked == True %}
          <form enctype="multipart/form-data" method="POST" action="{% url 'laundererRequestProcess' launderer.id %}">
            {% csrf_token %}
            <div class="form-group">
              <input type="hidden" id="statusField1" name="statusField" value="unblock">
            </div>
            <div class="form-group mt-4">
              <input type="submit" value="Unblock Launderer" onclick="return confirm('Are you sure you want to unblock this user?')" class="btn btn-md btn-outline-success px-4">
            </div>
          </form>
          {% endif %}
        </div>
      </div>

    </div>
  </section>


  <section class="charts">
    <div class="container-fluid">
      <h1> <a href="{% url 'adminLaunderetteDetail' launderette.id %}"> Launderer's Launderette </a></h1>
      <!-- Page Header-->
      <div class="card line-chart-example">
        <div class="card-header d-flex align-items-center">

          <img class="card-img-top" src="{{launderette.cover_photo.url}}" alt="{{launderette.cover_photo.url}}"
            width="300" height="600">
        </div>
        <div class="card-body">

          <p class="lead text-primary">Name:</p>
          <p class="lead ">{{launderette.name}}</p>
          <div class="row">
            <div class="col-6">
              <p class="lead text-primary">Location:</p>
              <p class="lead ">{{launderette.location}}</p>
            </div>
            <div class="col-6">

              <div class="col-6">
                <p class="lead text-primary">Available Time:</p>
                <p class="lead ">{{launderette.available_time}}</p>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer">

          <p class="lead text-primary">Date Joined:</p>
          <p class="lead ">{{launderette.date_joined}}</p>
          {% if launderette.isBlocked == False %}
          <form enctype="multipart/form-data" method="POST"
            action="{% url 'launderetteRequestProcess' launderette.id %}">
            {% csrf_token %}
            <div class="form-group">
              <input type="hidden" id="statusField1" name="statusField" value="block">
            </div>
            <div class="form-group mt-4">
              <input type="submit" value="Block Launderette" class="btn btn-md btn-outline-danger px-4">
            </div>
          </form>
          {% endif %}
          {% if launderette.isBlocked == True %}
          <form enctype="multipart/form-data" method="POST"
            action="{% url 'launderetteRequestProcess' launderette.id %}">
            {% csrf_token %}
            <div class="form-group">
              <input type="hidden" id="statusField1" name="statusField" value="unblock">
            </div>
            <div class="form-group mt-4">
              <input type="submit" value="Unblock Launderette" class="btn btn-md btn-outline-danger px-4">
            </div>
          </form>
          {% endif %}
        </div>
      </div>

    </div>
  </section>

  <footer class="main-footer">
    {% include 'frontend/admin/partialview/footer_navbar.html' %}
  </footer>
</div>


{% endblock content %}

frontend/templates/frontend/admin/review_details.html
{%  extends 'frontend/admin/partialview/base_template.html' %}
{% load static %}

{% block content %}


<div class="page">

  {% include 'frontend/admin/partialview/top_navbar.html' %}


  <!-- Breadcrumb-->
  <div class="breadcrumb-holder">
    <div class="container-fluid">
      <ul class="breadcrumb">
        <li class="breadcrumb-item "><a href="{% url 'adminDashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item "><a href="{% url 'adminReviews' %}">Reviews</a></li>
        <li class="breadcrumb-item active"><a>Details</a></li>
      </ul>
    </div>
  </div>

  <h1 class="h3 display-3 text-primary m-4 text-center"> Review Details </h1>

  <section class="charts">
    <div class="container-fluid">
      <!-- Page Header-->
      <div class="card line-chart-example">
        <div class="card-header d-flex align-items-center">
          <h4>Review</h4>
        </div>
        <div class="card-body">

          <div class="row">
            <div class="col-6">
              <p class="lead ">By:</p>
              <p class="lead "><a href="{% url 'adminClientDetail' review.client.id %}">{{review.client}}</a></p>
            </div>
            <div class="col-6">
              <p class="lead ">To:</p>
              <p class="lead "><a href="{% url 'adminLaunderetteDetail' review.launderette.id %}">{{review.launderette}}</a></p>
            </div>
          </div>
          <p class="lead text-primary">Review:</p>
          <p class="lead">{{review.review}}</p>

          <div class="row">
            <div class="col-6">
              <p class="lead text-primary">Rating:</p>
              <p class="lead ">{{review.rating}}</p>
            </div>
            <div class="col-6">

              <div class="col-6">
                <p class="lead text-primary">Sent Time:</p>
                <p class="lead ">{{review.date}}</p>
              </div>
            </div>
          </div>
        </div>
        <a class="btn btn-md btn-outline-primary  mx-4 mb-2 mt-4"
          href="{% url 'adminOrderDetails' review.order.id %} ">Check Order</a>
      </div>

    </div>
    <h4>Review Response</h4>

    {% for comment in comments %}
    <div class="container-fluid">
      <div class="card line-chart-example">
        <div class="card-header d-flex align-items-center">

        </div>
        <div class="card-body">

          <p class="lead text-primary">By:</p>
          {% if comment.client == None %}
          <p class="lead ">{{comment.launderette}}</p>
          {% else %}
          <p class="lead ">{{comment.client}}</p>
          {% endif %}

          <p class="lead text-primary">Comment:</p>
          <p class="lead">{{comment.comment}}</p>


          <div class="row">

            <div class="col-6">
              <p class="lead text-primary">Sent Time:</p>
              <p class="lead ">{{comment.date}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
  </section>

  <footer class="main-footer">
    {% include 'frontend/admin/partialview/footer_navbar.html' %}
  </footer>
</div>


{% endblock content %}